apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jekyll
  name: jekyll
  namespace: development
spec:
  ports:
  - name: 8080-4000
    nodePort: 30097
    port: 8080
    protocol: TCP
    targetPort: 4000
  selector:
    run: jekyll
  type: NodePort
status:
  loadBalancer: {}
