apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: file-server
  name: gop-fileserver
spec:
  containers:
    - image: kodekloud/fileserver
      name: gop-fileserver
      volumeMounts:
        - name: data-store
          mountPath: /web
  volumes:
    - name: data-store
      persistentVolumeClaim:
        claimName: data-pvc
status: {}
