apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: file-server
  name: gop-fs-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31200
  selector:
    run: file-server
  type: NodePort
status:
  loadBalancer: {}