apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: drupal-service
  name: drupal-service
spec:
  ports:
  - name: 80-8080
    nodePort: 30095
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: drupal
  type: NodePort
status:
  loadBalancer: {}
