apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: drupal
  name: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: drupal
    spec:
      initContainers:
      - image: drupal:8.6
        name: init-sites-volumes
        volumeMounts:
        - name: pvc
          mountPath: "/data"
        command: [ "/bin/bash", "-c"]
        args: [ 'cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R' ]
      containers:
      - image: drupal:8.6
        name: drupal
        resources: {}
        volumeMounts:
        - name: pvc
          mountPath: "/var/www/html/modules"
          subPath: modules
        - name: pvc
          mountPath: "/var/www/html/profiles"
          subPath: profiles
        - name: pvc
          mountPath: "/var/www/html/sites"
          subPath: sites
        - name: pvc
          mountPath: "/var/www/html/themes"
          subPath: themes
        ports:
        - containerPort: 80
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: drupal-pvc
      - name: workdir
        emptyDir: {}
status: {}


